export const FORM_PROJECT = "FORM_PROJECT";
export const GET_PROJECT = "GET_PROJECT";
export const ADD_PROJECT = "ADD_PROJECT";
export const FORM_VALIDATE = "FORM_VALIDATE";
export const CURRENT_PROJECT = "CURRENT_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const ERROR_PROJECT = "ERROR_PROJECT";

export const TASKS_PROJECT = "TASKS_PROJECT";
export const ADD_TASK = "ADD_TASK";
export const TASK_VALIDATE = "TASK_VALIDATE";
export const DELETE_TASK = "DELETE_TASK";
export const CURRENT_TASK = "CURRENT_TASK";
export const EDIT_TASK = "EDIT_TASK";
export const CLEAN_TASK = "CLEAN_TASK";

export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";

export const SUCCESSFULL_REGISTRATION = "SUCCESSFULL_REGISTRATION";
export const ERROR_REGISTRATION = "ERROR_REGISTRATION";
export const GET_USER = "GET_USER";
export const SUCCESSFULL_LOGIN = "SUCCESSFULL_LOGIN";
export const ERROR_LOGIN = "ERROR_LOGIN";
export const LOG_OUT = "LOG_OUT";
